import { Property } from '../types/Property';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Luxury 3BHK Apartment in Bandra West',
    price: 8500000,
    location: 'Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1200,
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Swimming Pool', 'Gym', 'Parking', 'Security', '24/7 Power Backup'],
    description: 'Beautiful 3BHK apartment with sea view in premium location',
    isNew: true,
    isFeatured: true
  },
  {
    id: '2',
    title: 'Modern Villa in Whitefield',
    price: 12000000,
    location: 'Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'villa',
    bedrooms: 4,
    bathrooms: 4,
    area: 2400,
    image: 'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Garden', 'Parking', 'Security', 'Clubhouse', 'Kids Play Area'],
    description: 'Spacious villa with modern amenities in IT corridor',
    isNew: false,
    isFeatured: true
  },
  {
    id: '3',
    title: '2BHK Flat in Sector 62',
    price: 4500000,
    location: 'Sector 62',
    city: 'Noida',
    state: 'Uttar Pradesh',
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    image: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Gym', 'Parking', 'Lift', 'Security'],
    description: 'Well-ventilated 2BHK flat in prime location',
    isNew: true,
    isFeatured: false
  },
  {
    id: '4',
    title: 'Independent House in Koramangala',
    price: 15000000,
    location: 'Koramangala',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'house',
    bedrooms: 5,
    bathrooms: 5,
    area: 3200,
    image: 'https://images.pexels.com/photos/1475938/pexels-photo-1475938.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Garden', 'Parking', 'Terrace', 'Study Room'],
    description: 'Spacious independent house perfect for large families',
    isNew: false,
    isFeatured: true
  },
  {
    id: '5',
    title: 'Penthouse in Cyber City',
    price: 18000000,
    location: 'Cyber City',
    city: 'Gurgaon',
    state: 'Haryana',
    type: 'apartment',
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    image: 'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Swimming Pool', 'Gym', 'Concierge', 'Valet Parking', 'Spa'],
    description: 'Luxury penthouse with panoramic city views',
    isNew: true,
    isFeatured: true
  },
  {
    id: '6',
    title: '1BHK Studio in Andheri East',
    price: 3200000,
    location: 'Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Security', 'Lift', 'Power Backup'],
    description: 'Compact studio apartment perfect for young professionals',
    isNew: false,
    isFeatured: false
  }
];

export const indianCities = [
  'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 
  'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 
  'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Pimpri-Chinchwad',
  'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik',
  'Faridabad', 'Meerut', 'Rajkot', 'Kalyan-Dombivali', 'Vasai-Virar',
  'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar',
  'Navi Mumbai', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore',
  'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur',
  'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubli-Dharwad', 'Bareilly',
  'Moradabad', 'Mysore', 'Gurgaon', 'Aligarh', 'Jalandhar', 'Tiruchirappalli',
  'Bhubaneswar', 'Salem', 'Warangal', 'Guntur', 'Bhiwandi', 'Saharanpur',
  'Gorakhpur', 'Bikaner', 'Amravati', 'Noida', 'Jamshedpur', 'Bhilai Nagar',
  'Cuttack', 'Firozabad', 'Kochi', 'Bhavnagar', 'Dehradun', 'Durgapur',
  'Asansol', 'Nanded-Waghala', 'Kolhapur', 'Ajmer', 'Gulbarga', 'Jamnagar',
  'Ujjain', 'Loni', 'Siliguri', 'Jhansi', 'Ulhasnagar', 'Nellore', 'Jammu',
  'Sangli-Miraj & Kupwad', 'Belgaum', 'Mangalore', 'Ambattur', 'Tirunelveli',
  'Malegaon', 'Gaya', 'Jalgaon', 'Udaipur', 'Maheshtala'
];