import { Property } from '../types/Property';

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Luxury 3BHK Apartment in Bandra",
    location: "Bandra West, Mumbai",
    city: "Mumbai",
    price: 25000000,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 1200,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Stunning 3BHK apartment with sea view in the heart of Bandra. Features modern amenities and premium finishes.",
    amenities: ["Swimming Pool", "Gym", "Security", "Parking", "Garden"],
    yearBuilt: 2020,
    parking: true,
    furnished: true
  },
  {
    id: 2,
    title: "Modern 2BHK in Koramangala",
    location: "Koramangala 4th Block, Bangalore",
    city: "Bangalore",
    price: 8500000,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Contemporary 2BHK apartment in prime Koramangala location with excellent connectivity.",
    amenities: ["Gym", "Security", "Parking", "Power Backup"],
    yearBuilt: 2019,
    parking: true,
    furnished: false
  },
  {
    id: 3,
    title: "Spacious Villa in Gurgaon",
    location: "DLF Phase 2, Gurgaon",
    city: "Gurgaon",
    price: 45000000,
    type: "villa",
    bedrooms: 4,
    bathrooms: 5,
    area: 2800,
    image: "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Luxurious 4BHK villa with private garden and modern amenities in prestigious DLF Phase 2.",
    amenities: ["Swimming Pool", "Garden", "Security", "Parking", "Gym", "Club House"],
    yearBuilt: 2018,
    parking: true,
    furnished: true
  },
  {
    id: 4,
    title: "Cozy Studio in Pune",
    location: "Hinjewadi Phase 1, Pune",
    city: "Pune",
    price: 3200000,
    type: "studio",
    bedrooms: 1,
    bathrooms: 1,
    area: 450,
    image: "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Compact and efficient studio apartment perfect for young professionals in IT hub.",
    amenities: ["Security", "Parking", "Power Backup"],
    yearBuilt: 2021,
    parking: true,
    furnished: true
  },
  {
    id: 5,
    title: "Heritage House in Old Delhi",
    location: "Chandni Chowk, Delhi",
    city: "Delhi",
    price: 15000000,
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "https://images.pexels.com/photos/1396125/pexels-photo-1396125.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Traditional house with modern renovations in the historic heart of Delhi.",
    amenities: ["Parking", "Garden", "Security"],
    yearBuilt: 1950,
    parking: true,
    furnished: false
  },
  {
    id: 6,
    title: "Sea View Apartment in Chennai",
    location: "Marina Beach Road, Chennai",
    city: "Chennai",
    price: 12000000,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    image: "https://images.pexels.com/photos/1396119/pexels-photo-1396119.jpeg?auto=compress&cs=tinysrgb&w=800",
    description: "Beautiful apartment with stunning sea views and beach access.",
    amenities: ["Swimming Pool", "Security", "Parking", "Beach Access"],
    yearBuilt: 2017,
    parking: true,
    furnished: true
  }
];